Elevator/Controllers/Bank/ManageBankController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Elevator.Models;
using Service.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using AutoMapper.QueryableExtensions;
using DataLayer.DTO.Products;
using Microsoft.Extensions.Configuration;
using Core;
using Core.BankCommon.ViewModels;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using Service.Repos.BankRepository;
using DataLayer.Entities.Bank;
using DataLayer.ViewModels.UsersPayments;
using Core.Utilities;
using System.Security.Claims;

namespace Elevator.Controllers
{
    [Authorize]
    public class ManageBankController : BaseController
    {
        private readonly BankConfig _bankConfig;
        private readonly UsersPaymentRepository _usersPaymentRepository;
        private readonly ShopProductRepository _shopProductRepository;
        private readonly ShopOrderRepository _shopOrderRepository;

        public ManageBankController(IConfiguration configuration
            , UsersPaymentRepository usersPaymentRepository
            , ShopProductRepository shopProductRepository
            , ShopOrderRepository shopOrderRepository)
        {
            _bankConfig = configuration.GetSection(nameof(BankConfig)).Get<BankConfig>();
            _usersPaymentRepository = usersPaymentRepository;
            _shopProductRepository = shopProductRepository;
            _shopOrderRepository = shopOrderRepository;
        }

        /// <summary>
        /// ایجاد درخواست برای اتصال به درگاه بانک
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> RequestBuilder(int id)
        {
            if (!User.Identity.IsAuthenticated) return RedirectToAction("Login", "Account");

            var cartInfo = await _shopOrderRepository.GetByIdAsync(id);

            if(cartInfo == null)
            {
                TempData.AddResult(SweetAlertExtenstion.Error("اطلاعات سبد خریدی با این عنوان یافت نشد"));
                return RedirectToAction("Index", "ShopProductController");
            }

            var OrderId = new Random().Next(1000, int.MaxValue).ToString();

            var dataBytes = Encoding.UTF8.GetBytes(string.Format("{0};{1};{2}", _bankConfig.TerminalId, OrderId, 1000));

            var symmetric = SymmetricAlgorithm.Create("TripleDes");
            symmetric.Mode = CipherMode.ECB;
            symmetric.Padding = PaddingMode.PKCS7;

            var encryptor = symmetric.CreateEncryptor(Convert.FromBase64String(_bankConfig.MerchantKey), new byte[8]);
            var SignData = Convert.ToBase64String(encryptor.TransformFinalBlock(dataBytes, 0, dataBytes.Length));

            var ReturnUrl = string.Format(_bankConfig.ReturnUrl);

            var ipgUri = string.Format("{0}/api/v0/Request/PaymentRequest", _bankConfig.PurchasePage);

            var data = new 
            {
                _bankConfig.TerminalId,
                _bankConfig.MerchantId,
                Amount= 1000,
                SignData,
                _bankConfig.ReturnUrl,
                LocalDateTime = DateTime.Now,
                OrderId,
                //MultiplexingData = request.MultiplexingData
            };

            var res = CallApi<BankResultViewModel>(ipgUri, data);
            res.Wait();

            if (res != null && res.Result != null)
            {
                if (res.Result.ResCode == "0")
                {
                    
                    await _usersPaymentRepository.MapAddAsync(SetValue(res.Result.Token));

                    Response.Redirect(string.Format("{0}/Purchase/Index?token={1}", _bankConfig.PurchasePage, res.Result.Token));
                }
                ViewBag.Message = res.Result.Description;
                return View();
            }

            return View();

            #region LocalMethods

            AddUserPaymentViewModel SetValue(string token)
            {
                var userId = User.Identity.FindFirstValue(ClaimTypes.NameIdentifier).ToInt();
                return new AddUserPaymentViewModel()
                {
                    Amount = data.Amount,
                    DateTime = data.LocalDateTime,
                    OrderId = data.OrderId,
                    Token = token,
                    UserId = UserId
                };
            }

            #endregion
        }

        /// <summary>
        /// بازگشت از درگاه
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public IActionResult CallBack(BankVerifyViewModel vm)
        {
            return View(vm);
        }
        
        /// <summary>
        /// تایید اطلاعات
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult VerifyRequest(BankVerifyViewModel vm)
        {
            try
            {
                //var cookie = Request.Cookies["Data"].Value;
                //var model = JsonConvert.DeserializeObject<PaymentRequest>(cookie);

                var model = _usersPaymentRepository.GetByCondition(a => a.OrderId == vm.OrderId && a.UserId == UserId);

                var dataBytes = Encoding.UTF8.GetBytes(vm.Token);

                var symmetric = SymmetricAlgorithm.Create("TripleDes");
                symmetric.Mode = CipherMode.ECB;
                symmetric.Padding = PaddingMode.PKCS7;

                var encryptor = symmetric.CreateEncryptor(Convert.FromBase64String(_bankConfig.MerchantKey), new byte[8]);

                var signedData = Convert.ToBase64String(encryptor.TransformFinalBlock(dataBytes, 0, dataBytes.Length));

                var data = new
                {
                    token = vm.Token,
                    SignData = signedData
                };

                var ipgUri = string.Format("{0}/api/v0/Advice/Verify", _bankConfig.PurchasePage);

                var res = CallApi<BankCallBackResultViewModel>(ipgUri, data);
                if (res != null && res.Result != null)
                {
                    if (res.Result.ResCode == "0")
                    {
                        vm.VerifyResultData = res.Result;
                        res.Result.Succeed = true;
                        ViewBag.Success = res.Result.Description;
                        return View("Verify");
                    }
                    ViewBag.Message = res.Result.Description;
                    return View("Verify");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.ToString();
            }

            return Redirect("/");
        }

        public static async Task<T> CallApi<T>(string apiUrl, object value)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Clear();
                var w = client.PostAsJsonAsync(apiUrl, value);
                w.Wait();
                HttpResponseMessage response = w.Result;
                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsAsync<T>();
                    result.Wait();
                    return result.Result;
                }
                return default(T);
            }
        }
    }
}

Elevator/Views/ManageBank/CallBack.cshtml
@model Core.BankCommon.ViewModels.BankVerifyViewModel

@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" style="direction: ltr">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @ViewBag.Message
    </div>
}

@using (Html.BeginForm("VerifyRequest", "ManageBank"))
{
    <div style="font-size: 20px; text-align: center; margin-top: 20px; margin-bottom: 20px">
        اطلاعات :
    </div>
    <div style="text-align: center; border: 1px solid #ccc">

        <div style="margin-top: 20px"></div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            کد پاسخ
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.ResCode
            @Html.HiddenFor(t => t.ResCode)
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            کلید توکن
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.Token
            @Html.HiddenFor(t => t.Token)
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            شماره سفارش
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.OrderId
            @Html.HiddenFor(t => t.OrderId)
        </div>

        <div id="traceno" style="margin-top: 20px; margin-bottom: 20px">
            <button type="submit" class="btn btn-primary">Verify</button>
        </div>
    </div>
}

@if (Model.VerifyResultData != null)
{
    <div style="font-size: 20px; text-align: center; margin-top: 20px; margin-bottom: 20px">
        اطلاعات دریافتی متد Verify
    </div>
    <div style="text-align: center; border: 1px solid #ccc">

        <div style="margin-top: 20px"></div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            کد پاسخ
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.VerifyResultData.ResCode
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            مبلغ
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.VerifyResultData.Amount
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            شماره سفارش
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.VerifyResultData.OrderId
        </div>

        <div style="margin-top: 20px; margin-bottom: 20px">
            شماره مرجع
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.VerifyResultData.RetrivalRefNo
        </div>

        <div style="margin-top: 20px; margin-bottom: 20px">
            شماره پیگیری
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.VerifyResultData.SystemTraceNo
        </div>

        <div style="margin-top: 20px; margin-bottom: 20px">
            توضیحات
        </div>
        <div style="margin-top: 20px; margin-bottom: 20px">
            @Model.VerifyResultData.Description
        </div>
    </div>
}