ElevatorAdmin/Areas/Product/Controllers/ManageProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper.QueryableExtensions;
using Core.CustomAttributes;
using Core.Utilities;
using DataLayer.DTO;
using DataLayer.DTO.ProductFeatures;
using DataLayer.DTO.Products;
using DataLayer.ViewModels;
using DataLayer.ViewModels.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Service.Repos;
using Service.Repos.Product;
using Service.Repos.User;
using WebFramework.Authenticate;
using WebFramework.Base;

namespace ElevatorAdmin.Areas.Product.Controllers
{
    [Area("Product")]
    [ControllerRole("مدیریت کالا‌ها")]
    public class ManageProductController : BaseAdminController
    {
        private readonly ProductRepostitory _productRepostitory;
        private readonly ProductGroupRepository _productGroupRepository;
        private readonly ProductUnitRepository _productUnitRepository;
        private readonly ProductGroupFeatureRepository _productGroupFeatureRepository;
        private readonly ProductFeatureRepository _productFeatureRepository;
        private readonly ProductGalleryRepository _productGalleryRepository;
        private readonly FeatureRepository _featureRepository;
        private readonly ProductDiscountRepository _productDiscountRepository;

        public ManageProductController(UsersAccessRepository usersAccessRepository,
            ProductRepostitory productRepostitory,
            ProductGroupRepository productGroupRepository,
            ProductUnitRepository productUnitRepository,
            ProductGroupFeatureRepository productGroupFeatureRepository,
            ProductFeatureRepository productFeatureRepository,
            ProductGalleryRepository productGalleryRepository,
            FeatureRepository featureRepository,
            ProductDiscountRepository productDiscountRepository) : base(usersAccessRepository)
        {
            _productRepostitory = productRepostitory;
            _productGroupRepository = productGroupRepository;
            _productUnitRepository = productUnitRepository;
            _productGroupFeatureRepository = productGroupFeatureRepository;
            _productFeatureRepository = productFeatureRepository;
            _productGalleryRepository = productGalleryRepository;
            _featureRepository = featureRepository;
            _productDiscountRepository = productDiscountRepository;
        }

        [ActionRole("صفحه لیست کالاها")]
        [HasAccess]
        public async Task<IActionResult> Index(ProductSearchViewModel searchModel = null)
        {
            var model = await _productRepostitory.LoadAsyncCount(
                this.CurrentPage,
                this.PageSize,
                searchModel);

            this.TotalNumber = model.Item1;

            ViewBag.Groups = await _productGroupRepository.GetListAsync();
            ViewBag.SearchModel = searchModel;

            return View(model.Item2);
        }

        [ActionRole("ثبت کالای جدید")]
        [HasAccess]
        public async Task<IActionResult> Create(int? id)
        {
            ViewBag.Units = await _productUnitRepository.GetListAsync();

            if (id != null) return View(id);
            ViewBag.Groups = await _productGroupRepository.GetListAsync();

     
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(ProductInsertViewModel product
            , ProductFeatureInsertViewModel vm
            , ProductGalleryViewModel Pics)
        {

            // ثبت محصول
            var productId = await _productRepostitory.SubmitProduct(product, Pics.file);

            vm.ProductId = productId;

            if (Pics.galleryImage != null)
            {
                // آپلود گالری
                await _productGalleryRepository.UploadGalley(Pics.galleryImage, productId);
            }

            // ویژگی ها
            await _productFeatureRepository.AddFeatureRange(vm);

            // نمایش پیغام
            TempData.AddResult(SweetAlertExtenstion.Ok());

            // بازگشت به لیست محصولات
            return Redirect(IndexUrlWithQueryString);
        }


        [ActionRole("ویرایش محصولات")]
        [HasAccess]
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Units = await _productUnitRepository.GetListAsync();
            ViewBag.Groups = await _productGroupRepository.GetListAsync();
            ViewBag.Gallery = await _productGalleryRepository.GetListAsync(a=>a.ProductId == id);

            var model = await _productRepostitory.GetByConditionAsync<ProductFullDTO>(a => a.Id == id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ProductUpdateViewModel product
            , ProductFeatureInsertViewModel vm
            , ProductGalleryViewModel Pics)
        {
            // ثبت محصول
            var productId = await _productRepostitory.UpdateProduct(product, Pics.file);
            vm.ProductId = product.Id;

            if (Pics.oldGallery != null)
            {
                // بررسی گالری عکس گذشته
                await _productGalleryRepository.UpdateRemindedGallery(Pics.oldGallery.Select(x => Convert.ToInt32(x)).ToList(), product.Id);
            }

            if (Pics.galleryImage != null)
            {
                // آپلود گالری
                await _productGalleryRepository.UploadGalley(Pics.galleryImage, productId);
            }

            if (vm.Items != null)
            {
                // ویژگی ها
                await _productFeatureRepository.UpdateFeatureRange(vm);
            }
            // نمایش پیغام
            TempData.AddResult(SweetAlertExtenstion.Ok());

            // بازگشت به لیست محصولات
            return Redirect(IndexUrlWithQueryString);
        }


        /// <summary>
        /// ویژگی های محصولات بر اساس ویژگی های محصول
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AllowAccess]
        public async Task<IActionResult> ProductFeatures(int id)
        {
            var groupFeature = await _productGroupFeatureRepository.GetFeaturesByGroupId(id);

            return PartialView(groupFeature);
        }

        /// <summary>
        /// ویژگی های محصولات بر اساس ویژگی های محصول
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<IActionResult> packageTest(int id)
        {
            var product = _productRepostitory.GetById(id);
            var groupFeature = await _productGroupFeatureRepository.GetFeaturesByGroupId(product.ProductGroupId);

            return View(groupFeature);
        }




        /// <summary>
        /// ویژگی های محصولات بر اساس ویژگی های محصول
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AllowAccess]
        public async Task<IActionResult> ProductFeaturesUpdate(int id, int productId)
        {
            var groupFeature = await _productGroupFeatureRepository.GetFeaturesByGroupId(id);

            var productFeature = await _productFeatureRepository
                .GetListAsync<ProductFeaturesFullDTO>(a => a.ProductId == productId);

            ViewBag.ProductFeature = productFeature;

            return PartialView(groupFeature);
        }


        #region ویرایش سریع قیمت
        [ActionRole("ویرایش سریع قیمت")]
        [HasAccess]
        public async Task<IActionResult> FastPriceEdit(int id)
        {
            var model = await _productRepostitory.GetByConditionAsync<ProductPriceDTO>(a => a.Id == id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> FastPriceEdit(ProductFastPriceEditViewModel vm)
        {
            await _productRepostitory.MapUpdateAsync(vm, vm.Id);

            TempData.AddResult(SweetAlertExtenstion.Ok());

            return Redirect(IndexUrlWithQueryString);
        }

        #endregion

        #region تغییر ویژگی 

        [ActionRole("تغییر ویژگی‌های کالا")]
        [HasAccess]
        public async Task<IActionResult> SubmitFeature(int id)
        {
            var model = await _productRepostitory.GetFeaturesValuesByProductId(id);

            ViewBag.ProductId = id;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SubmitFeature(ProductFeatureInsertViewModel vm)
        {
            var model = await _productFeatureRepository.UpdateFeatureRange(vm);

            TempData.AddResult(model);

            return Redirect(IndexUrlWithQueryString);
        }

        #endregion

        #region فعال / غیرفعال

        [ActionRole("فعال / غیر فعال کردن محصول")]
        public async Task<IActionResult> ChangeState(int id)
        {
            await _productRepostitory.ChangeStateProduct(id);

            TempData.AddResult(SweetAlertExtenstion.Ok());

            return Redirect(IndexUrlWithQueryString);
        }

        [ActionRole("تغییر محصول عادی به محصول ویژه")]
        public async Task<IActionResult> ChangeSpecialSell(int id)
        {
            await _productRepostitory.ChangeSpecial(id);

            TempData.AddResult(SweetAlertExtenstion.Ok());

            return Redirect(IndexUrlWithQueryString);
        }

        #endregion


        #region Delete


        [ActionRole("حذف محصول")]
        [HasAccess]
        public async Task<IActionResult> Delete(int Id)
        {

            return View(new DeleteDTO { Id = Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteViewModel model)
        {

            var result = await _productRepostitory.DeletedProduct(model.Id);
            TempData.AddResult(result);

            return Redirect(IndexUrlWithQueryString);
        }


        #endregion


        #region فرمول

ElevatorAdmin/Areas/Product/Views/ManageProduct/Create.cshtml
@using DataLayer.Entities
@model int?
@{
    ViewBag.Title = "ثبت کالای جدید";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var groups = ViewBag.Groups as List<ProductGroup>;
    var units = ViewBag.Units as List<ProductUnit>;

}


<script src="~/lib/ckeditor/ckeditor.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
<link href="~/lib/gallery/cms-create-form/cms-create-form.css" rel="stylesheet" />

<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link href="~/lib/Image-Uploader/ImageUploader.css" rel="stylesheet" />
<script src="~/lib/Image-Uploader/ImageUploader.js"></script>



<form class="form-horizontal" id="commentForm" method="post" style="" enctype="multipart/form-data">

    <div class="container">

        <div id="progressbarwizard" class="pull-in">
            <ul>
                <li><a href="#ProductInfo-2" data-toggle="tab">اطلاعات کالا</a></li>
                <li><a href="#Descriptor-2" data-toggle="tab">توضیحات</a></li>
                <li><a href="#Gallery-2" data-toggle="tab">تصاویر</a></li>
                <li><a href="#Feature-2" data-toggle="tab">ویژگی ها</a></li>
            </ul>

            <div class="tab-content b-0 m-b-0">

                <div id="bar" class="progress progress-striped progress-bar-primary-alt active">
                    <div class="bar progress-bar progress-bar-primary"></div>
                </div>

                <!--- اظلاعات کلی محصولات-->
                <div class="tab-pane p-t-10 fade" id="ProductInfo-2">
                    <div class="form-group">
                        <label for="Title" class="control-label col-sm-2">عنوان کالا <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            <input class="form-control" required="required" name="Title" aria-describedby="Title" placeholder="عنوان کالا" />
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="Title" class="control-label col-sm-2">قیمت کالا <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            @*<input type="number" class="form-control" required="required" name="Price" aria-describedby="Price" placeholder="قیمت کالا" />*@
                            <priceInput name="Price" title="قیمت کالا" required="true"></priceInput>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Title" class="control-label col-sm-2">وزن شاخص <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            <input name="ProductSize" type="number" placeholder="وزن شاخص" class="form-control" />

                        </div>
                    </div>


                    @if (Model == null)
                    {
                        <div class="form-group">
                            <label for="Title" class="control-label col-sm-2">گروه کالا <i class="text-danger fa fa-star size-8"></i></label>
                            <div class="col-sm-10">
                                <select class="form-control" name="ProductGroupId" required="required">
                                    <option value="">--لطفا انتخاب کنید--</option>
                                    @foreach (var item in groups)
                                    {
                                        <option value="@item.Id">@item.Title</option>
                                    }
                                </select>
                            </div>
                        </div>

                    }
                    else
                    {
                        <input type="hidden" name="ProductGroupId" value="@Model.Value" />

                        <script>
                            $(function () {
                                $('[name="ProductGroupId"]').on("change", function () {
                                    var groupId = $('[name="ProductGroupId"]').val();

                                    AjaxCall("/Product/ManageProduct/ProductFeatures", { id: groupId }, "POST", showResult);


                                    //$.get("/Product/ManageProduct/ProductFeatures", , function (result) {
                                    //    $('#Feature-2').html(result);
                                    //})

                                })

                                function showResult(result) {

                                    $('#Feature-2').html(result);
                                }


                            })


                        </script>
                    }




                    <div class="form-group">
                        <label for="Tags" class="control-label col-sm-2">واحد اندازه گیری کالا <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            <select class="form-control" name="ProductUnitId" required>
                                <option value="">--لطفا انتخاب کنید--</option>
                                @if (units != null)
                                {
                                    foreach (var item in units)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }
                                }
                            </select>
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="Tags" class="control-label col-sm-2">تگ‌های کالا </label>
                        <div class="col-sm-10">
                            <input type="text" value="" name="Tags" data-role="tagsinput" placeholder="افزودن تگ جدید" />
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="SearchKeyWord" class="control-label col-sm-2">کلید واژه‌های جستجو </label>
                        <div class="col-sm-10">
                            <input type="text" value="" name="SearchKeyWord" data-role="tagsinput" placeholder="افزودن کلید واژه جدید" />
                        </div>
                    </div>

                </div>

                <!--- توضیحات محصولات-->
                <div class="tab-pane p-t-10 fade" id="Descriptor-2">
                    <div class="form-group">
                        <label for="Text" class="control-label col-sm-2">توضیح کلی <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            <textarea name="Text" id="Text" class="form-control" aria-describedby="Text" required="required"></textarea>
                        </div>
                    </div>
             
                    <div class="form-group">
                        <label for="Text" class="control-label col-sm-2">توضیح مختصر <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            <textarea name="ShortDescription" id="Description" class="form-control" aria-describedby="ShortDescription" required="required"></textarea>
                        </div>
                    </div>
                </div>

                <!--- گالری تصاویر محصولات-->
                <div class="tab-pane p-t-10 fade" id="Gallery-2">


                    <div class="form-group">
                        <label for="Text" class="control-label col-sm-2">عکس اصلی محصول <i class="text-danger fa fa-star size-8"></i></label>
                        <div class="col-sm-10">
                            <input name="file"
                                   type="file" class="dropify"
                                   data-show-loader="true"
                                   accept="image/gif, image/jpeg, image/png , image/bmp , image/jpg"
                                   id="file" size="50">

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Text" class="control-label col-sm-2">گالری </label>
                        <div class="col-sm-10">

                            <div class="input-images-1" style="padding-top: .5rem;"></div>

                        </div>
                    </div>

                    <script>
                        $('.input-images-1').imageUploader({
                            imagesInputName: 'galleryImage',
                        });
                    </script>

                </div>

                <!--- ویژگی محصولات-->
                <div class="tab-pane p-t-10 fade" id="Feature-2">
                    <button type="submit" class="btn btn-block btn-success">ثبت</button>
                </div>
            </div>

            <div class="m-b-0 wizard col-lg-12 col-md-12 col-xl-12 col-sm-12">


                <ul class="pager m-b-0 wizard">

                    <li class="previous">
                        @*<div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">*@
                        <a href="#" class="btn btn-warning waves-effect waves-light">قبلی</a>
                        @*</div>*@
                    </li>

                    <li class="next"><a href="#" class="btn btn-primary waves-effect waves-light">بعد</a></li>
                </ul>

                @*<div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
                        <a href="#" class="btn btn-warning btn-block waves-effect waves-light">قبلی</a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
                        <a href="#" class="btn btn-primary btn-block waves-effect waves-light">بعد</a>
                    </div>*@

            </div>

        </div>

    </div>

</form>
<div class="col-lg-12 ">
    <a href="/Product/ManageProduct/Index" class="btn btn-danger btn-block waves-effect waves-light">بازگشت</a>
</div>

<style>
    textarea {
        resize: none
    }
</style>
<script>
    $('.dropify').dropify({
        messages: {
            'default': 'Drag and drop a file here or click',
            'replace': 'لطفا فایل خود را اینجا رها کنید',
            'remove': 'حذف',
            'error': 'خطایی رخ داده است'
        }
    });



</script>


<script type="text/javascript">
    $(document).ready(function () {
        CKEDITOR.replace('Text');

    });
</script>

<script>

    $(function () {
        $('[name="ProductGroupId"]').on("change", function () {
            $('#Feature-2').html(AjaxCall("/Product/ManageProduct/ProductFeatures", { id: $(this).val() }, "POST"));
        });




        $('#progressbarwizard').bootstrapWizard({
            onTabShow: function (tab, navigation, index) {
                var $total = navigation.find('li').length;
                var $current = index + 1;
                var $percent = ($current / $total) * 100;
                $('#progressbarwizard').find('.bar').css({ width: $percent + '%' });
            },
            'tabClass': 'nav nav-tabs navtab-wizard nav-justified bg-muted'
        });

        $('#btnwizard').bootstrapWizard({ 'tabClass': 'nav nav-tabs navtab-wizard nav-justified bg-muted', 'nextSelector': '.button-next', 'previousSelector': '.button-previous', 'firstSelector': '.button-first', 'lastSelector': '.button-last' });

        //var $validator = $("#commentForm").validate({
        //    rules: {
        //        emailfield: {
        //            required: true,
        //            email: true,
        //            minlength: 3
        //        },
        //        namefield: {
        //            required: true,
        //            minlength: 3
        //        },
        //        urlfield: {
        //            required: true,
        //            minlength: 3,
        //            url: true
        //        }
        //    }
        //});
    })

</script>
<script src="~/lib/gallery/cms-create-form/cms-create-form.js"></script>

ElevatorAdmin/Areas/Product/Views/ManageProduct/Delete.cshtml
@using DataLayer.DTO
@model DeleteDTO

@{
    Layout = null;
}


<form action="/Product/ManageProduct/Delete" class="form-horizontal" method="post" style="">

    <input type="hidden" value="@Model.Id" name="Id" />

    <div class="alert alert-warning" role="alert">

        <p class="" style="color:#000 !important">آیا از حذف اطمینان دارید؟</p>
        <hr>
        <p class="mb-0">

            <button type="submit" class="btn btn-block btn-danger">بلی</button>
            <button type="button" class="btn btn-block btn-success">خیر</button>
            
        </p>
    </div>



</form>

ElevatorAdmin/Areas/Product/Views/ManageProduct/FastPriceEdit.cshtml
@model DataLayer.DTO.Products.ProductPriceDTO

@{
    Layout = null;
}


<form id="frm" asp-action="FastPriceEdit" class="form-horizontal" method="post" style="">
    <div class="form-group mb-2">
        <div class="col-12 alert-info">
            <div class="alert ">
                @Model.Title
            </div>
        </div>
    </div>


    <div class="form-group">
        <label for="Title" class="control-label col-sm-3">قیمت کالا <i class="text-danger fa fa-star size-8"></i></label>
        <div class="col-sm-9">
            <input type="hidden" name="Id" value="@Model.Id" />
            <priceInput name="Price" title="قیمت کالا" required="true" value="@Model.Price">

            </priceInput>
        </div>
    </div>


    <button type="submit" class="btn btn-block btn-success" id="sbtForm">ثبت</button>


    <script>

    </script>
</form>

<script src="~/js/MSite.js"></script>

ElevatorAdmin/Areas/Product/Views/ManageProduct/FormulProduct.cshtml
@using DataLayer.DTO
@model List<NewsGroupDTO>
@{
    ViewData["Title"] = "ثبت خبر جدید";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="form-horizontal" method="post" style="" >

    <div class="col-12">
        <div class="container">

            <div class="form-group">
                <label for="Title" class="control-label col-sm-2">عنوان خبر <i class="text-danger fa fa-star size-8"></i></label>
                <div class="col-sm-10">
                    <textarea class="form-control" required="required" name="Title" aria-describedby="Title" placeholder="عنوان خبر"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="Text" class="control-label col-sm-2">متن خبر <i class="text-danger fa fa-star size-8"></i></label>
                <div class="col-sm-10">
                    <textarea name="Description" id="Description" class="form-control" placeholder="متن خبر" aria-describedby="Description" required="required"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="SummeryNews" class="control-label col-sm-2">خلاصه خبر <i class="text-danger fa fa-star size-8"></i></label>
                <div class="col-sm-10">
                    <textarea class="form-control" required="required" name="SummeryNews" aria-describedby="Title" placeholder="خلاصه خبر"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="Text" class="control-label col-sm-2">دسته بندی خبر <i class="text-danger fa fa-star size-8"></i></label>
                <div class="col-sm-10">
                    <select name="NewsGroupId" required="required" class="form-control form-control-lg">
                        <option>لطفا انتخاب کنید</option>
                        @foreach (var item in Model)
                        {
                            <option value="@item.Id">@item.Title</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="Text" class="control-label col-sm-2">عکس خبر <i class="text-danger fa fa-star size-8"></i></label>
                <div class="col-sm-10">
                    <input name="ImageFile"
                           required
                           type="file" class="dropify"
                           data-show-loader="true"
                           accept="image/gif, image/jpeg, image/png , image/bmp , image/jpg"
                           id="ImageAddress" size="50">

                </div>
            </div>

            <div class="form-group">
                <label for="Tags" class="control-label col-sm-2">تگ‌های خبر <i class="text-danger fa fa-star size-8"></i></label>
                <div class="col-sm-10">
                    <input type="text" required="required" value="" name="Tags" data-role="tagsinput" placeholder="افزودن تگ جدید" />
                </div>
            </div>


            <div class="form-group">
                <label for="IsActive" class="control-label col-sm-2">وضعیت</label>
                <div class="col-sm-10">
                    <div class="checkbox checkbox-primary" style="top:-10px;padding-left:0 !important">
                        <input type="checkbox" checked value="true" name="IsActive" data-role="IsActive" />

                        <label>

                        </label>
                    </div>

                </div>
            </div>

            <button type="submit" class="btn btn-block btn-success">ثبت</button>
                   
        </div>
    </div>
</form>

ElevatorAdmin/Areas/Product/Views/ManageProduct/SubmitFeature.cshtml
@using DataLayer.DTO.Feature
@model List<FeatureValueFullDetailDTO>
@{
    ViewBag.Title = " ویژگی‌های محصول";
}


<form asp-area="Product" asp-controller="ManageProduct" asp-action="SubmitFeature">
    <div class="col-lg-12 col-md-12 col-xl-12 col-sm-12">

        @{ int i = 0;}
        @* شماره محصول مورد نظر *@
        <input type="hidden" name="vm.ProductId" value="@ViewBag.ProductId" />

        @foreach (FeatureValueFullDetailDTO item in Model)
        {
            <input type="hidden" name="vm.Items[@i].FeatureId" value="@item.Id" />

            @if (item.FeatureType == DataLayer.SSOT.FeatureTypeSSOT.Fssot)
            {

                <div class="form-group">
                    <label for="Tags" class="control-label col-sm-2">
                        @item.Title
                        @if (item.IsRequired)
                        {
                            <i class="text-danger fa fa-star size-8"></i>
                        }
                    </label>
                    <div class="col-sm-10">
                        <select class="form-control" @(item.IsRequired ? "required" : "") name="vm.Items[@i].FeatureValue">
                            <option value="">--لطفا انتخاب کنید--</option>
                            @foreach (DataLayer.DTO.FeatureItem.FeatureItemDTO feature in item.FeatureItems)
                            {
                                if (item.Value.ToInt() == feature.Id)
                                {
                                    <option selected value="@feature.Id">@feature.Value</option>
                                }
                                else
                                {
                                    <option value="@feature.Id">@feature.Value</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    <label for="Text" class="control-label col-sm-2">
                        @item.Title
                        @if (item.IsRequired)
                        {
                            <i class="text-danger fa fa-star size-8"></i>
                        }
                    </label>
                    <div class="col-sm-10">

                        <input 
                               @(item.FeatureType==DataLayer.SSOT.FeatureTypeSSOT.Fint ? "step='0.01'" : "")
                               value="@item.Value" @(item.IsRequired ? "required" : "") 
                               type="@(item.FeatureType==DataLayer.SSOT.FeatureTypeSSOT.Fint?"number":"text")" 
                               placeholder="@item.Title" aria-describedby="Text" name="vm.Items[@i].FeatureValue" class="form-control" />
                    </div>
                </div>
            }
            i++;
        }


        <button type="submit" class="btn btn-block btn-success">ثبت</button>

    </div>
</form>